Algoritmo "Exercício_12"
// Funcao   : [Converter Fahrenheit em Celsius]
// Autor(a)   : Yan Moisés Rodrigues
// Data atual  : 17/03/2024
Var
   valor_fahrenheit:real
   valor_celsius:real
Inicio
      escreva ("Escreva a temperatura em ºF: ")
      leia (valor_fahrenheit)
      valor_celsius <- 5 / 9 * (valor_fahrenheit - 32)
      escreva (valor_fahrenheit, "ºF em celsius fica:", valor_celsius, "ºC")
Fimalgoritmo