Algoritmo "Exercício_13"
// Funcao   : Media ponderada
// Autor(a)   : Yan Moisés Rodrigues
// Data atual  : 17/03/2024
Var
   nota1:real
   nota2:real
   nota3:real
   total_media:real
Inicio
escreva ("Digite a primeira nota do aluno")
leia (nota1)
escreva ("Digite a segunda nota do aluno")
leia (nota2)
escreva ("Digite a terceira nota do aluno")
leia (nota3)
total_media <- (nota1 * 2 + nota2 * 3 + nota3 * 5) / 10
escreva ("A media final do aluno é:",total_media)
Fimalgoritmo