Algoritmo "Exercício_D"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Yan Moisés Rodrigues
// Data atual  : 19/04/2024
Var
   numero: inteiro

Inicio
   enquanto numero <= 20 faca
      se numero mod 2 <> 0 entao
         escreval(numero)
      fimse
      numero <- numero + 1
   fimenquanto

FimAlgoritmo